### ISSUE TITLE
ATAG - Overview

### ISSUE THREAD

**Issue by umbrabot** [umbraco/Umbraco-CMS.Accessibility.Issues#49]
### Authoring Tools and ATAG
Authoring tools are software and services that “authors” (web developers, designers, writers, etc.) use to produce web content (static web pages, dynamic web applications, etc.). Examples of authoring tools are listed below under “[Who ATAG is for]”.

The Authoring Tool Accessibility Guidelines (ATAG) documents explain how to:

- make the authoring tools themselves accessible, so that people with disabilities can create web content, **and**
- help authors create more accessible web content — specifically: enable, support, and promote the production of content that conforms to Web Content Accessibility Guidelines ([WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)).

ATAG is part of a series of accessibility guidelines, including the Web Content Accessibility Guidelines (WCAG) and the User Agent Accessibility Guidelines (UAAG). [Essential Components of Web Accessibility] https://www.w3.org/WAI/fundamentals/components/) explains the relationship between the different guidelines.

### Who ATAG is for
ATAG is primarily for developers of authoring tools, including the following types of authoring tools:

- web page authoring tools, for example, what-you-see-is-what-you-get (WYSIWYG) HTML editors
- software for generating websites, for example, content management systems (CMS) and learning management systems (LMS), courseware tools, content aggregators
- software that converts to web content technologies, for example, word processors and other office document applications with Save as HTML or EPUB
- multimedia authoring tools
- websites that let users add content, such as blogs, wikis, photo sharing sites, online forums, and social networking sites
- other types of tools listed in the glossary definition of [authoring tools](http://www.w3.org/TR/ATAG20/#def-Authoring-Tool)

ATAG and supporting resources are also intended to meet the needs of many different audiences, including policy makers, managers, and others. For example:

- People who want to [choose authoring tools](http://www.w3.org/WAI/impl/software) that are accessible and that produce accessible content can use ATAG to evaluate authoring tools.
- People who want to encourage their existing authoring tool developer to improve accessibility in future versions can refer the authoring tool vendor to ATAG.

### What is in ATAG 2.0
[ATAG 2.0](http://www.w3.org/TR/ATAG20/) has two main parts:

- Part A is about making the authoring tool itself accessible.
- Part B is about the authoring tool helping authors produce accessible content.

ATAG 2.0 is organized in layers:

- Principles provide high-level organization for the guidelines.
- Guidelines provide the framework and objectives for the success criteria.
- Success criteria are the accessibility requirements, which are written as testable statements, at [three levels](http://www.w3.org/TR/ATAG20/#intro_understand_levels_conformance): A, AA, AAA.

### ATAG at a Glance
_This comment provides a paraphrased summary of Authoring Tool Accessibility Guidelines (ATAG) 2.0. For the normative technical specification, see [www.w3.org/TR/ATAG20](http://www.w3.org/TR/ATAG20/)._

To learn about ATAG 2.0, please see the [ATAG Overview](http://www.w3.org/WAI/intro/atag.php).

### [Part A](http://www.w3.org/TR/ATAG20/#part_a): Make the authoring tool user interface accessible
[A1](http://www.w3.org/TR/ATAG20/#principle_a1) The authoring tool user interface follows applicable accessibility guidelines

- Ensure that web-based functionality is accessible
- Ensure that non-web-based functionality is accessible

[A2](http://www.w3.org/TR/ATAG20/#principle_a2) [Editing-views](http://www.w3.org/TR/ATAG20/#def-Editing-View) are perceivable

- Make alternative content available to authors
- Ensure that editing-view presentation can be [[programmatically determined](http://www.w3.org/TR/ATAG20/#def-Programmatically-Determined)]

[A3](http://www.w3.org/TR/ATAG20/#principle_a3) Editing-views are operable

- Provide keyboard access to authoring features
- Provide authors with enough time
- Help authors avoid flashing content that could cause seizures
- Enhance navigation and editing via content structure
- Provide text search of the content
- Allow users to manage preference settings
- Ensure that previews are at least as accessible as user agents

[A4](http://www.w3.org/TR/ATAG20/#principle_a4) Editing-views are understandable

- Help authors avoid and correct mistakes
- Document the user interface, including all accessibility features

### [Part B](http://www.w3.org/TR/ATAG20/#part_b): Support the production of accessible content
[B1](http://www.w3.org/TR/ATAG20/#principle_b1) Fully automatic processes produce accessible content

- Ensure that automatically-specified content is accessible
- Ensure that accessibility information is preserved

[B2](http://www.w3.org/TR/ATAG20/#principle_b2) Authors are supported in producing accessible content

- Ensure that accessible content production is possible
- Guide authors to produce accessible content
- Assist authors with managing alternative content for non-text content
- Assist authors with accessible templates
- Assist authors with accessible pre-authored content

[B3](http://www.w3.org/TR/ATAG20/#principle_b3) Authors are supported in improving the accessibility of existing content

- Assist authors in checking for accessibility problems
- Assist authors in repairing accessibility problems.

[B4](http://www.w3.org/TR/ATAG20/#principle_b4) Authoring tools promote and integrate their accessibility features

- Ensure the availability of features that support the production of accessible content
- Ensure that documentation promotes the production of accessible content

### Accessibility Cluster suggested features:

- [ ] [Tables creator](https://github.com/umbraco/Umbraco-CMS.Accessibility.Issues/issues/73)
- [ ] [Change language](https://github.com/umbraco/Umbraco-CMS.Accessibility.Issues/issues/74)
- [ ] [Text alternative](https://github.com/umbraco/Umbraco-CMS.Accessibility.Issues/issues/75)
- [ ] [Forms editor](https://github.com/umbraco/Umbraco-CMS.Accessibility.Issues/issues/76)
- [ ] [Video](https://github.com/umbraco/Umbraco-CMS.Accessibility.Issues/issues/77)
- [ ] [Documentation](https://github.com/umbraco/Umbraco-CMS.Accessibility.Issues/issues/82)
- [ ] [Live testing while authoring](https://github.com/umbraco/Umbraco-CMS.Accessibility.Issues/issues/78)
- [ ] [Testing of documents](https://github.com/umbraco/Umbraco-CMS.Accessibility.Issues/issues/79)
- [ ] [Testing the content of pages](https://github.com/umbraco/Umbraco-CMS.Accessibility.Issues/issues/80)
- [ ] [Testing the whole website](https://github.com/umbraco/Umbraco-CMS.Accessibility.Issues/issues/81)

Accessibility cluster main features: https://accessibilitycluster.com/main-results/presentation-of-the-features
Accessibility cluster Technical specifications: https://www.dropbox.com/s/5eglzznzcb8tui1/D1.3%20Technical%20specifications%20for%20the%20prioritised%20list%20of%20agreed%20accessibility%20features.pdf?dl=0

### Additional ATAG suggested features:

- [ ] [Video captions and transcripts](https://github.com/umbraco/Umbraco-CMS.Accessibility.Issues/issues/83)

**Comment by DannyLancaster** [comment]
### ATAG at a Glance

_This comment provides a paraphrased summary of Authoring Tool Accessibility Guidelines (ATAG) 2.0. For the normative technical specification, see [www.w3.org/TR/ATAG20](http://www.w3.org/TR/ATAG20/)._

To learn about ATAG 2.0, please see the [ATAG Overview](http://www.w3.org/WAI/intro/atag.php).

### [Part A](http://www.w3.org/TR/ATAG20/#part_a): Make the authoring tool user interface accessible

[A1](http://www.w3.org/TR/ATAG20/#principle_a1) The authoring tool user interface follows applicable accessibility guidelines

- Ensure that web-based functionality is accessible
- Ensure that non-web-based functionality is accessible

[A2](http://www.w3.org/TR/ATAG20/#principle_a2) [Editing-views](http://www.w3.org/TR/ATAG20/#def-Editing-View) are perceivable

- Make alternative content available to authors
- Ensure that editing-view presentation can be [[programmatically determined](http://www.w3.org/TR/ATAG20/#def-Programmatically-Determined)]

[A3](http://www.w3.org/TR/ATAG20/#principle_a3) Editing-views are operable

- Provide keyboard access to authoring features
- Provide authors with enough time
- Help authors avoid flashing content that could cause seizures
- Enhance navigation and editing via content structure
- Provide text search of the content
- Allow users to manage preference settings
- Ensure that previews are at least as accessible as user agents

[A4](http://www.w3.org/TR/ATAG20/#principle_a4) Editing-views are understandable

- Help authors avoid and correct mistakes
- Document the user interface, including all accessibility features


### [Part B](http://www.w3.org/TR/ATAG20/#part_b): Support the production of accessible content

[B1](http://www.w3.org/TR/ATAG20/#principle_b1) Fully automatic processes produce accessible content

- Ensure that automatically-specified content is accessible
- Ensure that accessibility information is preserved

[B2](http://www.w3.org/TR/ATAG20/#principle_b2) Authors are supported in producing accessible content

- Ensure that accessible content production is possible
- Guide authors to produce accessible content
- Assist authors with managing alternative content for non-text content
- Assist authors with accessible templates
- Assist authors with accessible pre-authored content

[B3](http://www.w3.org/TR/ATAG20/#principle_b3) Authors are supported in improving the accessibility of existing content

- Assist authors in checking for accessibility problems
- Assist authors in repairing accessibility problems.

[B4](http://www.w3.org/TR/ATAG20/#principle_b4) Authoring tools promote and integrate their accessibility features

- Ensure the availability of features that support the production of accessible content
- Ensure that documentation promotes the production of accessible content
